### ISSUE TITLE
Why is the mod marked as deprecated?

### ISSUE THREAD

**Issue by Shiranui-Izayoi** [Priscillalala/PersistentProfiles#1]
Less of an issue and more of a question. But why is the mod marked as deprecated on Thunderstore? Is it because it doesn't work? Or is it because it isn't needed anymore? It doesn't say anything anywhere. And from what I can tell none of the mods it depends on were deprecated either.

It is just strange that this seems to be one of the only mods deprecated. At least it is the only one that has been updated within the last 2 years that was deprecated. Did thunderstore automatically mark it as that or something else. Sorry am just confused.

**Comment by Priscillalala** [comment]
I mark this mod as deprecated after major updates just to be safe. I don't want to harm anyone's profiles in case it broke. I am not sure if it broke this update but I will undeprecate it once I confirm it still works safely/write any fixes.
